"""Refresh checked-in static SEO from SITE_MAP.json; not a website build/runtime."""
from pathlib import Path
import html,json,re
from xml.etree import ElementTree as ET
ROOT=Path(__file__).resolve().parents[3]
SITE=ROOT/'website'; RECORD=ROOT/'web_docs/chat-web7'
config=json.loads((RECORD/'SITE_MAP.json').read_text())
BASE=config['base_url']; assert BASE.startswith('https://') and BASE.endswith('/')
def canonical(path):
    return BASE+(path[:-10] if path.endswith('index.html') else path)
def main():
    for page in config['routes']:
        p=SITE/page['path']; text=p.read_text(); title=page['title']; description=page['description']; url=canonical(page['path'])
        text=re.sub(r'<title>.*?</title>',lambda m:'<title>'+html.escape(title)+'</title>',text,flags=re.S)
        text=re.sub(r'<meta name="description" content="[^"]*">',lambda m:'<meta name="description" content="'+html.escape(description,quote=True)+'">',text)
        graph=[{'@type':'WebSite','@id':BASE+'#website','url':BASE,'name':'CodeC','inLanguage':'en'},
               {'@type':'LearningResource' if page['legacy'].startswith('ch-') else 'WebPage','@id':url+'#page','url':url,'name':title,'description':description,'inLanguage':'en','isPartOf':{'@id':BASE+'#website'}}]
        if page['legacy'].startswith('ch-'):
            graph[1].update({'learningResourceType':'Tutorial','educationalLevel':'Beginner to intermediate','isPartOf':{'@id':canonical('learn/index.html')+'#course'}})
        if page['legacy']!='index.html':
            graph.append({'@type':'BreadcrumbList','@id':url+'#breadcrumbs','itemListElement':[{'@type':'ListItem','position':i+1,'name':crumb['name'],'item':canonical(crumb['path'])} for i,crumb in enumerate(page['breadcrumbs'])]})
            graph[1]['breadcrumb']={'@id':url+'#breadcrumbs'}
        if page['legacy']=='index.html':
            graph.append({'@type':'SoftwareApplication','@id':BASE+'#app','name':'CodeC','url':BASE,'description':'Open-source Android IDE with a code editor, built-in offline C compiler on supported ABIs, terminal and project tools.','applicationCategory':'DeveloperApplication','operatingSystem':'Android 7.0 or later','isAccessibleForFree':True,'downloadUrl':'https://github.com/pabi277/CodeC/releases','softwareVersion':'1.3.18','sameAs':['https://github.com/pabi277/CodeC']})
            graph[1]['about']={'@id':BASE+'#app'}
        if page['legacy']=='learn.html':
            graph.append({'@type':'Course','@id':url+'#course','url':url,'name':'Master CodeC from Zero to Advanced','description':description,'inLanguage':'en','isAccessibleForFree':True,'provider':{'@type':'Organization','name':'CodeC project','url':'https://github.com/pabi277/CodeC'},'hasPart':[{'@type':'LearningResource','@id':canonical(r['path'])+'#page','url':canonical(r['path']),'name':r['label']} for r in config['routes'] if r['legacy'].startswith('ch-')]})
        tags=[('property','og:type','website'),('property','og:site_name','CodeC'),('property','og:locale','en_US'),('property','og:title',title),('property','og:description',description),('property','og:url',url),('property','og:image',BASE+'assets/images/social-card.png'),('property','og:image:width','1200'),('property','og:image:height','630'),('property','og:image:alt','CodeC — write, compile and run C on Android. Offline compiler, editor, terminal and projects.'),('name','twitter:card','summary_large_image'),('name','twitter:title',title),('name','twitter:description',description),('name','twitter:image',BASE+'assets/images/social-card.png'),('name','twitter:image:alt','CodeC — C programming on Android')]
        block='  <!-- SEO:START — generated by web_docs/chat-web7/checks/refresh_seo.py -->\n'
        block+='  <link rel="canonical" href="'+html.escape(url,quote=True)+'">\n'
        block+='  <meta name="robots" content="index, follow, max-image-preview:large">\n'
        block+=''.join('  <meta '+attr+'="'+key+'" content="'+html.escape(value,quote=True)+'">\n' for attr,key,value in tags)
        block+='  <script type="application/ld+json">'+json.dumps({'@context':'https://schema.org','@graph':graph},ensure_ascii=False,separators=(',',':')).replace('<','\\u003c')+'</script>\n'
        block+='  <!-- SEO:END -->\n'
        text=re.sub(r'  <!-- SEO:START.*?<!-- SEO:END -->\n','',text,flags=re.S)
        text=text.replace('</head>',block+'</head>');p.write_text(text)
    ns='http://www.sitemaps.org/schemas/sitemap/0.9';ET.register_namespace('',ns)
    root=ET.Element('{'+ns+'}urlset')
    for page in sorted(config['routes'],key=lambda p:p['path']):
        node=ET.SubElement(root,'{'+ns+'}url');ET.SubElement(node,'{'+ns+'}loc').text=canonical(page['path'])
        ET.SubElement(node,'{'+ns+'}lastmod').text=page['last_modified']
    ET.indent(root,space='  ')
    (SITE/'sitemap.xml').write_bytes(ET.tostring(root,encoding='utf-8',xml_declaration=True)+b'\n')
    (SITE/'robots.txt').write_text('# Planned project site. Crawlers read robots.txt at the HOST root, not /CodeC/.\n# Coordinate this stanza with the host owner at publication; do not overwrite existing rules.\nUser-agent: *\nAllow: /CodeC/\n\nSitemap: '+BASE+'sitemap.xml\n')
    print('SEO refreshed:',len(config['routes']),'pages;',BASE)
if __name__=='__main__':main()
